import mysql.connector
mydb = mysql.connector.connect(
    host='localhost', user='root', password='dileepkumar@123', database='INVENTORY_MANAGEMENT')
cur = mydb.cursor()
tb = 'CREATE TABLE GOODS(GOODS_ID INT NOT NULL, NUMBER_ITEMS INT NOT NULL, MANUFACTURE_DATE DATE NOT NULL, PRODUCT_NAME VARCHAR(20) NOT NULL,COLOR VARCHAR(20) NOT NULL, PRIMARY KEY(PRODUCT_NAME, COLOR), FOREIGN KEY(MANUFACTURE_DATE) REFERENCES MANUFACTURE(MANUFACTURE_DATE) ON DELETE CASCADE)'
cur.execute(tb)