
import mysql.connector
mydb = mysql.connector.connect(
    host="localhost", user="root", password="dileepkumar@123", database="INVENTORY_MANAGEMENT")
cur = mydb.cursor()
t = "CREATE TABLE SALE(SALE_ID INT PRIMARY KEY NOT NULL,STORE_NAME VARCHAR(40) NOT NULL,SALE_DATE DATE NOT NULL,COLOR VARCHAR(10) NOT NULL,NUMBER_ITEMS INT NOT NULL,PRODUCT_NAME VARCHAR(20) NOT NULL,SALE_AMOUNT FLOAT NOT NULL,PROFIT_MARGIN FLOAT,FOREIGN KEY(PRODUCT_NAME, COLOR) REFERENCES GOODS(PRODUCT_NAME, COLOR) ON DELETE CASCADE)"
cur.execute(t)